# Generated by Django 6.0.5 on 2026-06-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_created_at_dojo_updated_at_ninja_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
    ]
